---
sudo: required
language: python

env:
  global:
    - ROLE_NAME: docker
  matrix:
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: debian9

services: docker

install:
  - pip install molecule docker

before_script:
#  - 'sudo docker pull ${distribution}:${version}'
#  - 'sudo docker build --no-cache --rm --file=molecule/default/files/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible molecule'
  - NAME=$(basename $(pwd)) ROLENAME=$(echo $NAME | sed -e s/ansible-//g) && cd .. &&  ln -fs $NAME $ROLENAME && cd $ROLENAME && pwd

script:
#  - TMPDIR=$(mktemp -d -t ci-XXXXXXXXXX) INSTANCE=$(basename $TMPDIR) molecule test
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
