- name: "install and configure exabgp"
  block:
  - name: "exabgp: disable arp check kernel paramters"
    sysctl:
      name: net.ipv4.conf.all.arp_filter
      value: "1"
      state: present
      reload: yes
    ignore_errors: yes

  - name: "exabgp: configure router advertisements kernel paramters"
    sysctl:
      name: "net.ipv6.conf.{{ item }}.accept_ra"
      value: "0"
      state: present
      reload: yes
    loop: "{{ ansible_interfaces }}"
    when:
    - not item | regex_search('lo' | string)
    - hostvars[inventory_hostname]['ansible_'~item]['ipv4'] is defined
    ignore_errors: yes

  - name: "exabgp: create user"
    user:
      name: exabgp
      comment: "ExaBGP"

  - name: "exabgp: install from pip"
    pip:
      name: exabgp
      executable: "{{ pip3_command }}"
    ignore_errors: '{{ ansible_check_mode }}'

  - name: "exabgp: checking directories exist"
    stat:
      path: "{{ item }}"
    register: folder_stats
    loop: "{{ required_dirs }}"

  - name: "exabgp: creating required directories"
    file:
      path: "{{ item.item.name }}"
      state: directory
      mode: "{{ item.item.perms }}"
      group: root
      owner: root
    when: not item.stat.exists
    loop: "{{ folder_stats.results }}"

  - name: "exabgp: install service"
    get_url:
      url: "https://raw.githubusercontent.com/Exa-Networks/exabgp/master/etc/systemd/exabgp.service"
      dest: "{{ exabgp_svc_path }}"
      mode: '0644'

  - name: "template: create configuration file"
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
#      owner: "{{ item.owner }}"
#      group: "{{ item.group }}"
      mode: "{{ item.mode }}"
    loop: "{{ required_tpls }}"

  - name: "exabgp: generate environment configuration"
    command: exabgp --fi > "{{ exabgp_env_path }}"
    become: yes
    changed_when: False

  - name: "exabgp: edit env params"
    ini_file:
      path: "{{ exabgp_env_path }}"
      section: "{{ item.section }}"
      option: "{{ item.option }}"
      value: "{{ item.value }}"
    loop: "{{ new_env_params }}"

  - name: "exabgp: add loopback device fix"
    lineinfile:
      create: yes
      path: /etc/sudoers.d/exabgp
      state: present
      mode: 0440
      regexp: '^nobody ALL='
      line: 'nobody ALL= NOPASSWD: /sbin/ip'
      validate: /usr/sbin/visudo -cf %s
    when: not ansible_check_mode and ansible_connection != "docker"

  - name: "exabgp: test configuration"
    command: exabgp --test "{{ exabgp_config_path }}"
    register: exabgp_test
    ignore_errors: yes
    changed_when: False

  - name: "exabgp: start service"
    systemd:
      state: started
      daemon_reload: yes
      name: exabgp
      enabled: yes
    when:
    - not ansible_check_mode
    - exabgp_test.rc == 0
    ignore_errors: '{{ ansible_check_mode }}'
    changed_when: False

  when: '"not found" not in pip_installed_version.stderr'
