---
- name: Load in project specific vars
  include_vars: "../vars/main.yml"

- name: exabgp set required directories
  set_fact:
    required_dirs: "{{ exabgp_dirs }}"

- name: exabgp set required templates
  set_fact:
    required_tpls: "{{ exabgp_templates }}"

- include: python.yml

- include: install.yml
